### ISSUE TITLE
problem with makeprior()

### ISSUE THREAD

**Issue by emilyostrow** [meganlsmith/delimitR-manual#10]
I am trying to run delimitr on a computing cluster and I am running into some issues with the makeprior() function. I am running a 3-taxon model and  delimitr seems to be having issues with something in the delimitR/SFS_CreateBinned_3pops.py file. I'm not sure if I potentially don't have something installed correctly or it is confused about the file structure, but I have made very few changes from the tutorial. Below is the error message I'm getting each time I try to run that code. Do you have any ideas why this might not be working? Thank you for your help.

`
R version 4.0.5 (2021-03-31) -- "Shake and Throw"
Copyright (C) 2021 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> Sys.setenv(RSTUDIO_PANDOC='/panfs/pfs.local/work/bi/bin/pandoc/bin');  rmarkdown::render('clusterDelimitr.Rmd',output_file='clusterDelimitr.html')

processing file: clusterDelimitr.Rmd

  |                                                                            
  |                                                                      |   0%
  |                                                                            
  |.......                                                               |  10%
  ordinary text without R code

  |                                                                            
  |..............                                                        |  20%
label: setup (with options) 
List of 1
 $ include: logi FALSE

  |                                                                            
  |.....................                                                 |  30%
  ordinary text without R code

  |                                                                            
  |............................                                          |  40%
label: fsc2 (with options) 
List of 1
 $ include: logi TRUE

  |                                                                            
  |...................................                                   |  50%
  ordinary text without R code

  |                                                                            
  |..........................................                            |  60%
label: postfsc2 (with options) 
List of 1
 $ include: logi TRUE

Traceback (most recent call last):
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 334, in <module>
Traceback (most recent call last):
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 334, in <module>
Traceback (most recent call last):
    Populate_AFS(file)
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 334, in <module>
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 326, in Populate_AFS
Traceback (most recent call last):
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 334, in <module>
Traceback (most recent call last):
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 334, in <module>
    Populate_AFS(file)
Traceback (most recent call last):
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 326, in Populate_AFS
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 334, in <module>
    Populate_AFS(file)
      File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 326, in Populate_AFS
Populate_AFS(file)
    Populate_AFS(file)
      File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 326, in Populate_AFS
setvalues(Full_AFS,line)
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 326, in Populate_AFS
        setvalues(Full_AFS,line)
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 31, in setvalues
Populate_AFS(file)
      File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 31, in setvalues
setvalues(Full_AFS,line)
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 326, in Populate_AFS
Traceback (most recent call last):
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 31, in setvalues
      File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 334, in <module>
setvalues(Full_AFS,line)
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 31, in setvalues
    raise ValueError('Value list is not the same length as the '
    raise ValueError('Value list is not the same length as the '
Traceback (most recent call last):
      File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 334, in <module>
ValueErrorraise ValueError('Value list is not the same length as the '
    ValueError:     setvalues(Full_AFS,line)
    : Value list is not the same length as the OrderedDict.raise ValueError('Value list is not the same length as the '
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 31, in setvalues
setvalues(Full_AFS,line)
Value list is not the same length as the OrderedDict.ValueError
ValueError    
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 31, in setvalues
    : : Populate_AFS(file)
    Populate_AFS(file)
Value list is not the same length as the OrderedDict.Value list is not the same length as the OrderedDict.raise ValueError('Value list is not the same length as the '
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 326, in Populate_AFS

  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 326, in Populate_AFS
ValueError    : raise ValueError('Value list is not the same length as the '
Value list is not the same length as the OrderedDict.
ValueError:     Value list is not the same length as the OrderedDict.setvalues(Full_AFS,line)

      File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 31, in setvalues
setvalues(Full_AFS,line)
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 31, in setvalues
    raise ValueError('Value list is not the same length as the '
    raise ValueError('Value list is not the same length as the '
ValueError: Value list is not the same length as the OrderedDict.ValueError
: Value list is not the same length as the OrderedDict.
Traceback (most recent call last):
Traceback (most recent call last):
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 334, in <module>
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 334, in <module>
    Populate_AFS(file)
    Populate_AFS(file)
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 326, in Populate_AFS
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 326, in Populate_AFS
        setvalues(Full_AFS,line)
setvalues(Full_AFS,line)
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 31, in setvalues
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 31, in setvalues
    raise ValueError('Value list is not the same length as the '
    raise ValueError('Value list is not the same length as the '
ValueErrorValueError: : Value list is not the same length as the OrderedDict.Value list is not the same length as the OrderedDict.

Traceback (most recent call last):
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 334, in <module>
    Populate_AFS(file)
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 326, in Populate_AFS
    setvalues(Full_AFS,line)
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 31, in setvalues
    raise ValueError('Value list is not the same length as the '
ValueError: Value list is not the same length as the OrderedDict.
Traceback (most recent call last):
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 334, in <module>
    Populate_AFS(file)
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 326, in Populate_AFS
    setvalues(Full_AFS,line)
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 31, in setvalues
    raise ValueError('Value list is not the same length as the '
ValueError: Value list is not the same length as the OrderedDict.
Traceback (most recent call last):
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 334, in <module>
    Populate_AFS(file)
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 326, in Populate_AFS
    setvalues(Full_AFS,line)
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 31, in setvalues
    raise ValueError('Value list is not the same length as the '
ValueError: Value list is not the same length as the OrderedDict.
Traceback (most recent call last):
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 334, in <module>
    Populate_AFS(file)
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 326, in Populate_AFS
    setvalues(Full_AFS,line)
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 31, in setvalues
    raise ValueError('Value list is not the same length as the '
ValueError: Value list is not the same length as the OrderedDict.
Traceback (most recent call last):
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 334, in <module>
Traceback (most recent call last):
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 334, in <module>
Traceback (most recent call last):
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 334, in <module>
Traceback (most recent call last):
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 334, in <module>
    Populate_AFS(file)
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 326, in Populate_AFS
    Populate_AFS(file)
    Populate_AFS(file)
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 326, in Populate_AFS
      File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 326, in Populate_AFS
setvalues(Full_AFS,line)
    Populate_AFS(file)
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 31, in setvalues
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 326, in Populate_AFS
    raise ValueError('Value list is not the same length as the '
ValueError: Value list is not the same length as the OrderedDict.
    setvalues(Full_AFS,line)
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 31, in setvalues
    setvalues(Full_AFS,line)
    raise ValueError('Value list is not the same length as the '
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 31, in setvalues
    setvalues(Full_AFS,line)
ValueError: Value list is not the same length as the OrderedDict.
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 31, in setvalues
    raise ValueError('Value list is not the same length as the '
ValueError: Value list is not the same length as the OrderedDict.
    raise ValueError('Value list is not the same length as the '
ValueError: Value list is not the same length as the OrderedDict.
Traceback (most recent call last):
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 334, in <module>
    Populate_AFS(file)
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 326, in Populate_AFS
    setvalues(Full_AFS,line)
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 31, in setvalues
    raise ValueError('Value list is not the same length as the '
ValueError: Value list is not the same length as the OrderedDict.
Traceback (most recent call last):
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 334, in <module>
    Populate_AFS(file)
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 326, in Populate_AFS
    setvalues(Full_AFS,line)
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 31, in setvalues
    raise ValueError('Value list is not the same length as the '
ValueError: Value list is not the same length as the OrderedDict.
Traceback (most recent call last):
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 334, in <module>
    Populate_AFS(file)
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 326, in Populate_AFS
    setvalues(Full_AFS,line)
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 31, in setvalues
    raise ValueError('Value list is not the same length as the '
ValueError: Value list is not the same length as the OrderedDict.
Traceback (most recent call last):
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 334, in <module>
    Populate_AFS(file)
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 326, in Populate_AFS
    setvalues(Full_AFS,line)
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 31, in setvalues
    raise ValueError('Value list is not the same length as the '
ValueError: Value list is not the same length as the OrderedDict.
Traceback (most recent call last):
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 334, in <module>
    Populate_AFS(file)
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 326, in Populate_AFS
    setvalues(Full_AFS,line)
Traceback (most recent call last):
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 31, in setvalues
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 334, in <module>
    raise ValueError('Value list is not the same length as the '
ValueError: Value list is not the same length as the OrderedDict.
    Populate_AFS(file)
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 326, in Populate_AFS
    setvalues(Full_AFS,line)
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 31, in setvalues
    raise ValueError('Value list is not the same length as the '
ValueError: Value list is not the same length as the OrderedDict.
Traceback (most recent call last):
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 334, in <module>
    Populate_AFS(file)
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 326, in Populate_AFS
    setvalues(Full_AFS,line)
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 31, in setvalues
    raise ValueError('Value list is not the same length as the '
ValueError: Value list is not the same length as the OrderedDict.
Traceback (most recent call last):
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 334, in <module>
    Populate_AFS(file)
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 326, in Populate_AFS
    setvalues(Full_AFS,line)
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 31, in setvalues
    raise ValueError('Value list is not the same length as the '
ValueError: Value list is not the same length as the OrderedDict.
Traceback (most recent call last):
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 334, in <module>
    Populate_AFS(file)
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 326, in Populate_AFS
    setvalues(Full_AFS,line)
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 31, in setvalues
    raise ValueError('Value list is not the same length as the '
ValueError: Value list is not the same length as the OrderedDict.
Traceback (most recent call last):
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 334, in <module>
    Populate_AFS(file)
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 326, in Populate_AFS
    setvalues(Full_AFS,line)
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 31, in setvalues
    raise ValueError('Value list is not the same length as the '
ValueError: Value list is not the same length as the OrderedDict.
Traceback (most recent call last):
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 334, in <module>
    Populate_AFS(file)
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 326, in Populate_AFS
    setvalues(Full_AFS,line)
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 31, in setvalues
    raise ValueError('Value list is not the same length as the '
ValueError: Value list is not the same length as the OrderedDict.
Traceback (most recent call last):
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 334, in <module>
    Populate_AFS(file)
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 326, in Populate_AFS
    setvalues(Full_AFS,line)
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 31, in setvalues
    raise ValueError('Value list is not the same length as the '
ValueError: Value list is not the same length as the OrderedDict.
Traceback (most recent call last):
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 334, in <module>
    Populate_AFS(file)
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 326, in Populate_AFS
    setvalues(Full_AFS,line)
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 31, in setvalues
    raise ValueError('Value list is not the same length as the '
ValueError: Value list is not the same length as the OrderedDict.
Traceback (most recent call last):
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 334, in <module>
    Populate_AFS(file)
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 326, in Populate_AFS
    setvalues(Full_AFS,line)
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 31, in setvalues
    raise ValueError('Value list is not the same length as the '
ValueError: Value list is not the same length as the OrderedDict.
Traceback (most recent call last):
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 334, in <module>
    Populate_AFS(file)
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 326, in Populate_AFS
    setvalues(Full_AFS,line)
  File "/panfs/pfs.local/work/bi/e001o910/programs/rlibs/delimitR/SFS_CreateBinned_3pops.py", line 31, in setvalues
    raise ValueError('Value list is not the same length as the '
ValueError: Value list is not the same length as the OrderedDict.
mkdir: cannot create directory ‘Prior’: File exists
cp: cannot stat ‘Binned_Processed_updatedMigBuboAll_1_MSFS.obs’: No such file or directory
cp: cannot stat ‘Binned_Processed_updatedMigBuboAll_10_MSFS.obs’: No such file or directory
cp: cannot stat ‘Binned_Processed_updatedMigBuboAll_11_MSFS.obs’: No such file or directory
cp: cannot stat ‘Binned_Processed_updatedMigBuboAll_12_MSFS.obs’: No such file or directory
cp: cannot stat ‘Binned_Processed_updatedMigBuboAll_13_MSFS.obs’: No such file or directory
cp: cannot stat ‘Binned_Processed_updatedMigBuboAll_14_MSFS.obs’: No such file or directory
cp: cannot stat ‘Binned_Processed_updatedMigBuboAll_15_MSFS.obs’: No such file or directory
cp: cannot stat ‘Binned_Processed_updatedMigBuboAll_16_MSFS.obs’: No such file or directory
cp: cannot stat ‘Binned_Processed_updatedMigBuboAll_17_MSFS.obs’: No such file or directory
cp: cannot stat ‘Binned_Processed_updatedMigBuboAll_18_MSFS.obs’: No such file or directory
cp: cannot stat ‘Binned_Processed_updatedMigBuboAll_19_MSFS.obs’: No such file or directory
cp: cannot stat ‘Binned_Processed_updatedMigBuboAll_2_MSFS.obs’: No such file or directory
cp: cannot stat ‘Binned_Processed_updatedMigBuboAll_20_MSFS.obs’: No such file or directory
cp: cannot stat ‘Binned_Processed_updatedMigBuboAll_21_MSFS.obs’: No such file or directory
cp: cannot stat ‘Binned_Processed_updatedMigBuboAll_22_MSFS.obs’: No such file or directory
cp: cannot stat ‘Binned_Processed_updatedMigBuboAll_23_MSFS.obs’: No such file or directory
cp: cannot stat ‘Binned_Processed_updatedMigBuboAll_24_MSFS.obs’: No such file or directory
cp: cannot stat ‘Binned_Processed_updatedMigBuboAll_25_MSFS.obs’: No such file or directory
cp: cannot stat ‘Binned_Processed_updatedMigBuboAll_26_MSFS.obs’: No such file or directory
cp: cannot stat ‘Binned_Processed_updatedMigBuboAll_27_MSFS.obs’: No such file or directory
cp: cannot stat ‘Binned_Processed_updatedMigBuboAll_28_MSFS.obs’: No such file or directory
cp: cannot stat ‘Binned_Processed_updatedMigBuboAll_29_MSFS.obs’: No such file or directory
cp: cannot stat ‘Binned_Processed_updatedMigBuboAll_3_MSFS.obs’: No such file or directory
cp: cannot stat ‘Binned_Processed_updatedMigBuboAll_30_MSFS.obs’: No such file or directory
cp: cannot stat ‘Binned_Processed_updatedMigBuboAll_31_MSFS.obs’: No such file or directory
cp: cannot stat ‘Binned_Processed_updatedMigBuboAll_32_MSFS.obs’: No such file or directory
cp: cannot stat ‘Binned_Processed_updatedMigBuboAll_33_MSFS.obs’: No such file or directory
cp: cannot stat ‘Binned_Processed_updatedMigBuboAll_4_MSFS.obs’: No such file or directory
cp: cannot stat ‘Binned_Processed_updatedMigBuboAll_5_MSFS.obs’: No such file or directory
cp: cannot stat ‘Binned_Processed_updatedMigBuboAll_6_MSFS.obs’: No such file or directory
cp: cannot stat ‘Binned_Processed_updatedMigBuboAll_7_MSFS.obs’: No such file or directory
cp: cannot stat ‘Binned_Processed_updatedMigBuboAll_8_MSFS.obs’: No such file or directory
cp: cannot stat ‘Binned_Processed_updatedMigBuboAll_9_MSFS.obs’: No such file or directory
Quitting from lines 87-105 (clusterDelimitr.Rmd) 
Error in file(file, "rt") : cannot open the connection
Calls: <Anonymous> ... makeprior -> assign -> <Anonymous> -> read.table -> file

Execution halted
`

**Comment by meganlsmith** [comment]
Hi Emily,

It is likely something with your traits file. Can you share your input files and R script, so that I can try to reproduce the error and find the cause?

Best,
Megan


Megan Smith
NSF Postdoctoral Fellow
Department of Biology
Indiana University, Bloomington, IN

**Comment by emilyostrow** [comment]
The files are in the .zip file. I made the SFS using easysfs. Thank you for your help!

[BuboDelimitRInput.zip](https://github.com/meganlsmith/delimitR/files/10007956/BuboDelimitRInput.zip)

**Comment by meganlsmith** [comment]
Hi Emily,

No problem! It seems the number of lines in your trait file does not match the number of samples used to build your SFS. In the SFS, you have 62, 88, and 35 samples from populations 0, 1, and 2, respectively, but in the SFS you have 39, 53, and 23 samples. This is probably due to down-sampling.  easySFS is set up a bit differently than my original scripts, and so the output does not work as seamlessly as would be ideal with deliimitR. You only need to provide a trait file with the down-sampled number of haploid individuals for each species (i.e., you need two lines per individual if your species is diploid). The actual sample labels will not matter. So just make sure your traits file has 62, 88, and 35 samples labeled as populations 0,1, and 2, and things should run smoothly! Again, sorry for the confusion; I should update this to run more seamlessly with the easySFS output. 

Don’t hesitate to let me know if you have any other questions!


Thanks!
Megan
Megan Smith
NSF Postdoctoral Fellow
Department of Biology
Indiana University, Bloomington, IN

**Comment by emilyostrow** [comment]
Thanks for your speedy help! I used the wrong ploidy with easysfs, which doubled the sample size I thought I had and then removed some number. I didn't even think of removing those individuals from the traits file. It all makes sense now and I am attempting to run through the program again.

**Comment by meganlsmith** [comment]
You’re welcome. Glad I was able to help!

Megan Smith
NSF Postdoctoral Fellow
Department of Biology
Indiana University, Bloomington, IN
